
spring:
    application:
        name: gateway
    datasource:
        url: jdbc:h2:mem:mydb
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

server:
    port: 3000

security:
    jwt:
        public-key-path: ./jwt-public-pkcs8.pem
        algorithm: RS256
        expiration-time: 900000