
spring:
    application:
        name: auth
    datasource:
        url: jdbc:h2:mem:mydb
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

server:
    port: 3000

security:
    jwt:
        user-public-key-path: ./user_public_key.pem
        internal-public-key-path: ./internal_public_key.pem
        algorithm: RS256
        user-expiration-time: 900000
        internal-expiration-time: 900000