
spring:
    application:
        name: auth
    datasource:
        url: ${DB_URL}
        driverClassName: ${DB_DRIVER}
        password: ${DB_PASSWORD}
        username: ${DB_USERNAME}
    jpa:
        database-platform: ${DB_PLATFORM}
        hibernate:
            ddl-auto: create-drop
    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

server:
    port: 3000

security:
    jwt:
        user-public-key-path: ${USER_JWT_PUBLIC_KEY_PATH}
        user-private-key-path: ${USER_JWT_PRIVATE_KEY_PATH}
        internal-public-key-path: ${INTERNAL_JWT_PUBLIC_KEY_PATH}
        user-expiration-time: ${USER_JWT_EXPIRATION_TIME}
        internal-expiration-time: ${INTERNAL_JWT_EXPIRATION_TIME}
        algorithm: ${JWT_ALG}