spring.application.name=auth
server.port=3002

security.jwt.secret-key=929e25302972f80fd56b0d8a2ea1221ae9eb06361cf801ca86bc09645f275f882533bb8c4ad87ec149b718999d297b5b2ca94729cb8eb2edf2927b9960e5624c

security.jwt.public-key-path=/Users/olivi/Code/url_shortener/auth/src/main/resources/jwt-public-pkcs8.pem
security.jwt.private-key-path=/Users/olivi/Code/url_shortener/auth/src/main/resources/jwt-private-pkcs8.pem
security.jwt.algorithm=RS256
security.jwt.expiration-time=900000

spring.datasource.url=jdbc:postgresql://localhost:5432/test-db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=dev
spring.datasource.password=dev
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest